# Generated by Django 4.2.13 on 2024-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_avg_rate_alter_productimagemodel_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='avg_rate',
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='file',
            field=models.ImageField(upload_to='product/extra-img/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='image',
            field=models.ImageField(default='/default/product-image.png', upload_to='product/img/%Y/%m/%d/'),
        ),
    ]
